cam_model: Pinhole
cameras:
  - cam_id: 0
    cam_width: 960
    cam_height: 720
    cam_fx: 460.46212917
    cam_fy: 460.36186539
    cam_cx: 486.84584172
    cam_cy: 375.42452885
    cam_d0: 0.04621996
    cam_d1: -0.04881841
    cam_d2: -0.0000643
    cam_d3: 0.0002615
  
  - cam_id: 1
    cam_width: 960
    cam_height: 720
    cam_fx: 450.0
    cam_fy: 450.0
    cam_cx: 480.0
    cam_cy: 360.0
    cam_d0: 0.05
    cam_d1: -0.05
    cam_d2: 0.0
    cam_d3: 0.0
  
  - cam_id: 2
    cam_width: 960
    cam_height: 720
    cam_fx: 470.0
    cam_fy: 470.0
    cam_cx: 490.0
    cam_cy: 370.0
    cam_d0: 0.04
    cam_d1: -0.04
    cam_d2: 0.0
    cam_d3: 0.0

